
using namespace std;

class EDivisionPorCero : public exception{

public:
       virtual const char* what() const throw()
       {
       return "División por cero";
       }
} edivporcero;
